### ISSUE TITLE
Make Loading Text component

### ISSUE THREAD

**Issue by iOiurson** [iOiurson/open-books#129]
Find a way to display loading state on a text [with a CSS gradient](https://cssgradient.io/blog/css-gradient-text/).

Other examples:
https://fossheim.io/writing/posts/css-text-gradient/
https://codepen.io/leocampos/pen/pPwwNR

**Comment by iOiurson** [comment]
`background-clip: text` is not standard, this might not be a good idea.

**Comment by GermainGrumel** [comment]
PR : 
https://github.com/iOiurson/open-books/pull/143
