### ISSUE TITLE
Integrate Typescript

### ISSUE THREAD

**Issue by iOiurson** [iOiurson/open-books#4]
For now, Svelte [does not support Typescript out of the box](https://github.com/sveltejs/svelte/issues/1639), but there is some [community-driven alternatives](https://github.com/sveltejs/sapper/issues/760) to dig through.

**Comment by Zimtir** [comment]
https://github.com/Zimtir/SENT-template template with Sapper + Express + Node + Typescript
Try to use right now! :)

**Comment by antony** [comment]
Also note https://github.com/sveltejs/svelte/issues/4518
